export const users = [
  { id: 1, name: "Ali Khan", email: "ali.khan@gmail.com", age: 22 },
  { id: 2, name: "Sara Ahmed", email: "sara.ahmed@gmail.com", age: 24 },
  { id: 3, name: "Usman Tariq", email: "usman.tariq@gmail.com", age: 21 },
  { id: 4, name: "Ayesha Noor", email: "ayesha.noor@gmail.com", age: 23 },
  { id: 5, name: "Hamza Malik", email: "hamza.malik@gmail.com", age: 25 },
  { id: 6, name: "Fatima Ali", email: "fatima.ali@gmail.com", age: 20 },
  { id: 7, name: "Bilal Hussain", email: "bilal.hussain@gmail.com", age: 26 },
  { id: 8, name: "Zainab Khan", email: "zainab.khan@gmail.com", age: 22 },
  { id: 9, name: "Ahmed Raza", email: "ahmed.raza@gmail.com", age: 27 },
  { id: 10, name: "Hira Javed", email: "hira.javed@gmail.com", age: 24 },
  { id: 11, name: "Muneeb Shah", email: "muneeb.shah@gmail.com", age: 23 },
  { id: 12, name: "Iqra Bibi", email: "iqra.bibi@gmail.com", age: 21 },
  { id: 13, name: "Talha Khan", email: "talha.khan@gmail.com", age: 28 },
  { id: 14, name: "Laiba Noor", email: "laiba.noor@gmail.com", age: 20 },
  { id: 15, name: "Saad Ullah", email: "saad.ullah@gmail.com", age: 25 },
  { id: 16, name: "Maham Ali", email: "maham.ali@gmail.com", age: 22 },
  { id: 17, name: "Danish Iqbal", email: "danish.iqbal@gmail.com", age: 29 },
  { id: 18, name: "Komal Khan", email: "komal.khan@gmail.com", age: 23 },
  { id: 19, name: "Fahad Raza", email: "fahad.raza@gmail.com", age: 26 },
  { id: 20, name: "Anaya Malik", email: "anaya.malik@gmail.com", age: 21 },
];
